// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org.turnera.core.proto/packet.proto

package org.turnera.core.model.protobuf;

public final class PacketProto {
  private PacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.turnera.core.model.protobuf.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
     */
    boolean hasPacketType();
    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
     */
    org.turnera.core.model.protobuf.PacketProto.Packet.PacketType getPacketType();

    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    boolean hasData();
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * <pre>
   *syntax = "proto3";
   * </pre>
   *
   * Protobuf type {@code org.turnera.core.model.protobuf.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.turnera.core.model.protobuf.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      packetType_ = 1;
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.turnera.core.model.protobuf.PacketProto.Packet.PacketType value = org.turnera.core.model.protobuf.PacketProto.Packet.PacketType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                packetType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              data_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.turnera.core.model.protobuf.PacketProto.internal_static_org_turnera_core_model_protobuf_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.turnera.core.model.protobuf.PacketProto.internal_static_org_turnera_core_model_protobuf_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.turnera.core.model.protobuf.PacketProto.Packet.class, org.turnera.core.model.protobuf.PacketProto.Packet.Builder.class);
    }

    /**
     * <pre>
     * 包的类型
     * </pre>
     *
     * Protobuf enum {@code org.turnera.core.model.protobuf.Packet.PacketType}
     */
    public enum PacketType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 心跳包
       * </pre>
       *
       * <code>HEARTBEAT = 1;</code>
       */
      HEARTBEAT(1),
      /**
       * <pre>
       * 非心跳包
       * </pre>
       *
       * <code>DATA = 2;</code>
       */
      DATA(2),
      ;

      /**
       * <pre>
       * 心跳包
       * </pre>
       *
       * <code>HEARTBEAT = 1;</code>
       */
      public static final int HEARTBEAT_VALUE = 1;
      /**
       * <pre>
       * 非心跳包
       * </pre>
       *
       * <code>DATA = 2;</code>
       */
      public static final int DATA_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PacketType valueOf(int value) {
        return forNumber(value);
      }

      public static PacketType forNumber(int value) {
        switch (value) {
          case 1: return HEARTBEAT;
          case 2: return DATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PacketType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
              public PacketType findValueByNumber(int number) {
                return PacketType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.turnera.core.model.protobuf.PacketProto.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final PacketType[] VALUES = values();

      public static PacketType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PacketType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.turnera.core.model.protobuf.Packet.PacketType)
    }

    private int bitField0_;
    public static final int PACKETTYPE_FIELD_NUMBER = 1;
    private int packetType_;
    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
     */
    public boolean hasPacketType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
     */
    public org.turnera.core.model.protobuf.PacketProto.Packet.PacketType getPacketType() {
      @SuppressWarnings("deprecation")
      org.turnera.core.model.protobuf.PacketProto.Packet.PacketType result = org.turnera.core.model.protobuf.PacketProto.Packet.PacketType.valueOf(packetType_);
      return result == null ? org.turnera.core.model.protobuf.PacketProto.Packet.PacketType.HEARTBEAT : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPacketType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, packetType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packetType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.turnera.core.model.protobuf.PacketProto.Packet)) {
        return super.equals(obj);
      }
      org.turnera.core.model.protobuf.PacketProto.Packet other = (org.turnera.core.model.protobuf.PacketProto.Packet) obj;

      boolean result = true;
      result = result && (hasPacketType() == other.hasPacketType());
      if (hasPacketType()) {
        result = result && packetType_ == other.packetType_;
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPacketType()) {
        hash = (37 * hash) + PACKETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + packetType_;
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.turnera.core.model.protobuf.PacketProto.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.turnera.core.model.protobuf.PacketProto.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *syntax = "proto3";
     * </pre>
     *
     * Protobuf type {@code org.turnera.core.model.protobuf.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.turnera.core.model.protobuf.Packet)
        org.turnera.core.model.protobuf.PacketProto.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.turnera.core.model.protobuf.PacketProto.internal_static_org_turnera_core_model_protobuf_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.turnera.core.model.protobuf.PacketProto.internal_static_org_turnera_core_model_protobuf_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.turnera.core.model.protobuf.PacketProto.Packet.class, org.turnera.core.model.protobuf.PacketProto.Packet.Builder.class);
      }

      // Construct using org.turnera.core.model.protobuf.PacketProto.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.turnera.core.model.protobuf.PacketProto.internal_static_org_turnera_core_model_protobuf_Packet_descriptor;
      }

      @java.lang.Override
      public org.turnera.core.model.protobuf.PacketProto.Packet getDefaultInstanceForType() {
        return org.turnera.core.model.protobuf.PacketProto.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public org.turnera.core.model.protobuf.PacketProto.Packet build() {
        org.turnera.core.model.protobuf.PacketProto.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.turnera.core.model.protobuf.PacketProto.Packet buildPartial() {
        org.turnera.core.model.protobuf.PacketProto.Packet result = new org.turnera.core.model.protobuf.PacketProto.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packetType_ = packetType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.turnera.core.model.protobuf.PacketProto.Packet) {
          return mergeFrom((org.turnera.core.model.protobuf.PacketProto.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.turnera.core.model.protobuf.PacketProto.Packet other) {
        if (other == org.turnera.core.model.protobuf.PacketProto.Packet.getDefaultInstance()) return this;
        if (other.hasPacketType()) {
          setPacketType(other.getPacketType());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPacketType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.turnera.core.model.protobuf.PacketProto.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.turnera.core.model.protobuf.PacketProto.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int packetType_ = 1;
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
       */
      public boolean hasPacketType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
       */
      public org.turnera.core.model.protobuf.PacketProto.Packet.PacketType getPacketType() {
        @SuppressWarnings("deprecation")
        org.turnera.core.model.protobuf.PacketProto.Packet.PacketType result = org.turnera.core.model.protobuf.PacketProto.Packet.PacketType.valueOf(packetType_);
        return result == null ? org.turnera.core.model.protobuf.PacketProto.Packet.PacketType.HEARTBEAT : result;
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
       */
      public Builder setPacketType(org.turnera.core.model.protobuf.PacketProto.Packet.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        packetType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>required .org.turnera.core.model.protobuf.Packet.PacketType packetType = 1;</code>
       */
      public Builder clearPacketType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>optional string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.turnera.core.model.protobuf.Packet)
    }

    // @@protoc_insertion_point(class_scope:org.turnera.core.model.protobuf.Packet)
    private static final org.turnera.core.model.protobuf.PacketProto.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.turnera.core.model.protobuf.PacketProto.Packet();
    }

    public static org.turnera.core.model.protobuf.PacketProto.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.turnera.core.model.protobuf.PacketProto.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_turnera_core_model_protobuf_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_turnera_core_model_protobuf_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#org.turnera.core.proto/packet.proto\022\037o" +
      "rg.turnera.core.model.protobuf\"\205\001\n\006Packe" +
      "t\022F\n\npacketType\030\001 \002(\01622.org.turnera.core" +
      ".model.protobuf.Packet.PacketType\022\014\n\004dat" +
      "a\030\002 \001(\t\"%\n\nPacketType\022\r\n\tHEARTBEAT\020\001\022\010\n\004" +
      "DATA\020\002B.\n\037org.turnera.core.model.protobu" +
      "fB\013PacketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_turnera_core_model_protobuf_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_turnera_core_model_protobuf_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_turnera_core_model_protobuf_Packet_descriptor,
        new java.lang.String[] { "PacketType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
